version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: daily
    labels:
      - automerge
  - package-ecosystem: pip
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: daily
    labels:
      - automerge
