version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/.ci'
    schedule:
      interval: 'daily'
    labels:
      - 'automerge'
    open-pull-requests-limit: 10
  - package-ecosystem: 'pip'
    directory: '/.ci'
    schedule:
      interval: 'daily'
    labels:
      - 'automerge'
    open-pull-requests-limit: 10
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'automerge'
    open-pull-requests-limit: 10
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'automerge'
    open-pull-requests-limit: 10
