jupyter_book_task:
  env:
    GH_TOKEN: ENCRYPTED[!4e97045f3d90ba1ee046e291414b73f3ad3b5151f8259e93e7773dce32c2346606e82e67544eadc765ba8113ae9ac2b6!]
    JULIA_NUM_THREADS: '4'
  auto_cancellation: true
  container:
    dockerfile: .ci/Dockerfile
    cpu: 4
    memory: 16G
    use_in_memory_disk: true
  notebook_script: |
    find docs/ -type f -name "*.ipynb" -print0 | parallel -0 -j4 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace {}
  build_script: |
    jupyter-book build docs --warningiserror --keep-going -v
  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     ghp-import -n docs/_build/html
  #     git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
  #   fi
