# Using "merge_request into main" workflow (https://docs.gitlab.com/ee/ci/yaml/workflow.html)
include:
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"

stages:
  - build
  - test
  - deploy

# GitLab CI: Auto dependency updates https://thacoon.com/posts/gitlab-ci-auto-dependency-update/
# `GIT_PUSH_TOKEN` CI/CD variable = personal access token (PAT) with write access
update-julia:
  image: julia:1.7
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JULIA_PKG_PRECOMPILE_AUTO: 0
  script:
    - apt-get update && apt-get install -y --no-install-recommends git
    - julia --color=yes --threads=auto --project=@. -e 'import Pkg; Pkg.update()'
    # Open a MR when there is a update, requires GIT_PUSH_TOKEN` CI/CD variable = personal access token (PAT) with write access
    - |
      if [[ -n $(git status --porcelain) ]]; then
        echo "Commiting updates"
        NEW_BR=auto-update-$(date '+%Y-%m-%d-%H-%M-%S')
        git config --global user.name "${GITLAB_USER_NAME}"
        git config --global user.email "${GITLAB_USER_EMAIL}"
        git checkout -b ${NEW_BR}
        git add .
        git commit -m "${NEW_BR}"
        git push "https://${GITLAB_USER_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" \
            -o merge_request.create \
            -o merge_request.target="${CI_DEFAULT_BRANCH}" \
            -o merge_request.merge_when_pipeline_succeeds \
            -o merge_request.remove_source_branch \
            -o merge_request.title="${NEW_BR}" \
            -o merge_request.label="automated update" \
            -o merge_request.assign="${GITLAB_USER_NAME}"
        exit;
      else
        echo "no change, nothing to commit"
      fi

# Taken from https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/
# Build docker images and tag it by git SHA
build-docker:
  image: docker:20.10
  # Your runner
  tags:
    - md705
  # We're using socket binding so dind is not needed
  # services:
  #   - docker:20.10-dind
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      -f docker/Dockerfile
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# Default: main = latest
push-docker:
  image: docker:20.10
  services:
    - docker:20.10-dind
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
  variables:
    GIT_STRATEGY: none
    TAG: "latest"
  script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$TAG
    - docker push $CI_REGISTRY_IMAGE:$TAG

push-tag-docker:
  extends: push-docker
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    TAG: $CI_COMMIT_TAG

build-notebooks:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - md705
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    - key:
        files:
          - Manifest.toml
          - requirements.txt
        prefix: jb
      paths:
        - docs/_build/
  script:
    # Uncomment if you want parallel notebook execution
    # - find docs -type f -name "*.ipynb" -print0 | parallel -0 -j2 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --ExecutePreprocessor.kernel_name=julia-1.7 --execute --inplace {}
    - jupyter-book build docs
  artifacts:
    paths:
      - docs/_build/

pages:
  extends: build-notebooks
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
  script:
    - jupyter-book build docs
    - mv docs/_build/html public
    # - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip -f -k {} \; -exec  -f -k {} \; || echo 'Compression failed. Skipping...'
  artifacts:
    paths:
      - public
