name: Build Jupyter Book

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JULIA_NUM_THREADS: 2
  JULIA_VER: "1.7"
  PYTHON_VER: "3.10"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Restore Python virtualenv
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - name: Download Pip cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: Install Python dependencies if cache miss
        run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: Setup Julia ${{ env.JULIA_VER }}
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ env.JULIA_VER }}
      - name: Cache Julia
        uses: actions/cache@v3
        env:
          cache-name: "julia-01"
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/compiled
            ~/.julia/packages
            ~/.julia/registries
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}-
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install Julia dependencies
        run: |
          julia --project=@. -e 'using Pkg; Pkg.instantiate()'
          julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.build("IJulia")'
      - name: Cache Jupyter book outputs
        uses: actions/cache@v3
        env:
          cache-name: "jb-01"
        with:
          path: docs/_build/.jupyter_cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/Manifest.toml', 'requirements.txt') }}-${{ hashFiles('docs/**/*.md', 'docs/**/*.ipynb') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/Manifest.toml', 'requirements.txt') }}

      - name: Build Jupyter Books
        run: jb build docs --warningiserror --keep-going -v

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: docs/_build/html
          full_commit_message: ${{ github.event.head_commit.message }}
