name: CI with dynamic parallel matrix

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TIMEOUT: '-1'    # nbconvert timeout
  EXTRA_ARGS: ''   # Extra arguments for nbconvert
  JULIA_CPU_TARGET: 'generic;haswell,clone_all'
  JULIA_NUM_THREADS: 'auto'
  JULIA_CONDAPKG_BACKEND: 'Current'
  JULIA_CI: 'true'
  JULIA_CACHE_NUM: '1'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      hash: ${{ steps.cache.outputs.hash }}
      jlver: ${{ steps.read_toml.outputs.value }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        cache-environment: true
    - name: Read Julia version
      uses: SebRollen/toml-action@v1.0.2
      id: read_toml
      with:
        file: 'Manifest.toml'
        field: 'julia_version'
    - name: Install Julia using jill.sh
      run: |
        wget -O /tmp/jill.sh https://raw.githubusercontent.com/abelsiqueira/jill/main/jill.sh
        bash /tmp/jill.sh --version ${{ steps.read_toml.outputs.value }} -y
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Calculate cache key
      id: cache
      run: echo hash=${{ hashFiles('src/**','Project.toml', 'Manifest.toml')}} >> "$GITHUB_OUTPUT"
    - name: Cache Julia deps
      uses: actions/cache@v3
      with:
        path: |
          ~/.julia
          ~/.local/share/jupyter/kernels
        key: ${{ runner.os }}-jill-${{ env.JULIA_CACHE_NUM }}-${{ steps.cache.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-jill-${{ env.JULIA_CACHE_NUM }}-
    - name: Install Julia deps
      shell: micromamba-shell {0}
      run: |
        julia --color=yes -e 'using Pkg; Pkg.Registry.update(); Pkg.add(["IJulia"])'
        julia --project=@. --color=yes -e 'using Pkg, Dates; Pkg.instantiate(); Pkg.gc(collect_delay=Day(1))'
    - name: List notebooks as a JSON array
      id: set-matrix
      shell: micromamba-shell {0}
      working-directory: docs
      run: echo "matrix=$(python -c 'import glob, json; print(json.dumps(glob.glob("**/*.ipynb", recursive=True)))')" >> "$GITHUB_OUTPUT"

  execute:
    needs: setup
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        # Notebooks need to be executed
        notebook: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Restore notebook if present
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: docs/${{ matrix.notebook }}
          key: ${{ runner.os }}-notebook-${{ hashFiles(format('docs/{0}', matrix.notebook)) }}-${{ needs.setup.outputs.hash }}
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          environment-file: environment.yml
          cache-environment: true
      - name: Install Julia using jill.sh
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          wget -O /tmp/jill.sh https://raw.githubusercontent.com/abelsiqueira/jill/main/jill.sh
          bash /tmp/jill.sh --version ${{ needs.setup.outputs.jlver }} -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Cache Julia deps
        uses: actions/cache/restore@v3
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          path: |
            ~/.julia
            ~/.local/share/jupyter/kernels
          key: ${{ runner.os }}-jill-${{ env.JULIA_CACHE_NUM }}-${{ needs.setup.outputs.hash }}
      - name: Precompile Julia stuff if needed
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        shell: micromamba-shell {0}
        run: |
          julia --color=yes -e 'import IJulia; IJulia.installkernel("Julia", "--project=@.")'
          julia --project=@. --color=yes -e 'using Pkg, Dates; Pkg.instantiate(); Pkg.precompile()'
      - name: Execute Notebook
        shell: micromamba-shell {0}
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: >
          jupyter nbconvert --to notebook --execute --inplace ${{ env.EXTRA_ARGS }}
          --ExecutePreprocessor.timeout=${{ env.TIMEOUT }}
          --ExecutePreprocessor.kernel_name=julia-1.$(julia -e 'print(VERSION.minor)')
          docs/${{ matrix.notebook }}
      - name: Cache notebook
        uses: actions/cache/save@v3
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          path: docs/${{ matrix.notebook }}
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - name: Upload Notebook
        uses: actions/upload-artifact@v3
        with:
          name: notebooks
          path: docs*/${{ matrix.notebook }}  # keep folder structure
          retention-days: 1

  render:
    needs: execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download notebooks
        uses: actions/download-artifact@v3
        with:
          name: notebooks
          path: out/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: out
      - name: Copy back built notebooks
        run: cp --verbose -rf out/docs/* docs/
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
      - name: Build website
        shell: micromamba-shell {0}
        run: jupyter-book build --path-output public/ docs/
      - name: Upload pages artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  # CI conclusion for GitHub status check
  # Adaped from https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
  CI:
    needs: render
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{ needs.render.result }} == "success" ]]; then
            echo "Tests passed"
            exit 0
          else
            echo "Tests failed"
            exit 1
          fi

  # Deployment job
  deploy:
    name: Deploy to GitHub pages
    needs: render
    if: ${{ github.ref == 'refs/heads/main' }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
