name: Build Jupyter Book Website

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JULIA_VERSION: "1.7"
  PYTHON_VERSION: "3.9"
  JULIA_NUM_THREADS: 2

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore Python virtualenv
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - name: Download Pip cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: Install Python dependencies if cache miss
        run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # Julia
      - name: Setup Julia ${{ env.JULIA_VERSION }}
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ env.JULIA_VERSION }}
      - name: Cache Julia Depot
        uses: actions/cache@v3
        env:
          cache-name: "Julia"
        with:
          path: ~/.julia/
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.JULIA_VERSION }}-${{ hashFiles('Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ env.JULIA_VERSION }}-
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install Julia dependencies
        shell: julia --color=yes --threads=auto --project=@. {0}
        env:
          PYTHON: python
        run: |
          using Pkg
          Pkg.instantiate()
          Pkg.resolve()
          Pkg.precompile()
      - name: Install IJulia
        shell: julia --color=yes --threads=auto {0}
        env:
          PYTHON: python
        run: |
          using Pkg
          Pkg.add("IJulia")
          Pkg.build("IJulia")

      # Jupyer book
      - name: Cache Jupyter book outputs
        uses: actions/cache@v3
        env:
          cache-name: "jb-03"
        with:
          path: docs/_build/.jupyter_cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Manifest.toml', 'requirements.txt') }}-${{ hashFiles('docs/**/*.md', 'docs/**/*.ipynb') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Manifest.toml', 'requirements.txt') }}-
      - name: Build Jupyter Books
        run: jb build docs --warningiserror --keep-going

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: docs/_build/html
          full_commit_message: ${{ github.event.head_commit.message }}
