name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/linkcheck.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    env:
      DIR: 'docs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: jb
          create-args: >-
            python>=3.11
            jupyter-book
            docutils>=0.17.1,<0.18|>=0.20
          cache-environment: true
          post-cleanup: all
      - name: Build website
        shell: micromamba-shell {0}
        run: jupyter-book build ${DIR} --builder linkcheck
