name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sosiristseng/docker-jupyterbook:0.13.1
    steps:
      - uses: actions/checkout@v3
      - run: jupyter-book build docs/ --builder linkcheck
