name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month

env:
  PYTHON_VER: '3.10'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER }}
          cache: 'pip'
          cache-dependency-path: '.ci/requirements.txt'
      - name: Install dependencies
        run: pip install -r .ci/requirements.txt
      - name: Check Links
        run: jupyter-book build docs/ --builder linkcheck
