name: Test Julia Package

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JULIA_NUM_THREADS: 2

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["1.7"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1.2.0
      - uses: julia-actions/julia-runtest@v1.7.0
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2.1.0
        with:
          files: lcov.info
