name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week

env:
  JULIA_VER: '1.8.1'
  JULIA_PKG_PRECOMPILE_AUTO: '0'

jobs:
  update-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Julia ${{ env.JULIA_VER }}
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ env.JULIA_VER }}
      - name: Update Julia dependencies
        run: julia --color=yes --project=@. --threads=auto -e 'import Pkg; Pkg.update()'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Package Update
          token: ${{ secrets.PAT }} # PAT with repo access
          labels: |
            automerge
