name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week

jobs:
  update-notebook:
    runs-on: ubuntu-latest
    container:
      image: julia:1.8.3
    steps:
      - run: apt-get update && apt-get install -y git
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Julia dependencies
        env:
          JULIA_PKG_PRECOMPILE_AUTO: '0'
        run: julia --color=yes --project=@. --threads=auto -e 'import Pkg; Pkg.update()'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Package Update
          token: ${{ secrets.PAT }} # PAT with repo access
          labels: |
            automerge
